### PR TITLE
Support Github enterprise

### PR DESCRIPTION
**Pull request by nathanleiby**
## JIRA
n/a

## Overview
Allows microplane to work with Github enterprise.

Caveat noted in README: _Self-hosted Github setup with different URLs for the main API and uploads API are not yet supported. If this is a blocker for you, please file an issue or make a PR._ 

## Testing
- [ ] Test e2e with a Github enterprise setup :octocat: 💰 
- [x] Test e2e with normal Github setup :octocat: to verify no regressions

### CODE REVIEW

**Comment by nathanleiby** [comment]
@Line-Noise @gtorre @VasuBhaskar hoping to land this soon. 

- Before (building from this branch yourself) or after that (downloading the latest release), would any of you be able to verify whether the change works for you? 
- A related question: do you use different URLs for the main API and uploads API in your setups? 

Thank you!

--

Personally, I still haven't had a chance to get a working setup for Github enterprise. The simplest option for me seems like it would require running it myself on AWS. I've also reached out to their developer program seeking a developer license to work on enterprise, instead of using a free trial for Github enterprise.

**Comment by Line-Noise** [comment]
I'm happy to give this a test. I'm not sure about the upload URL. I doubt it's different but I don't know how to check.

**Comment by gtorre** [comment]
@nathanleiby I'd be happy to test the changes.

> A related question: do you use different URLs for the main API and uploads API in your setups?

Same URL.

**Review by ghirsch1 — APPROVED** [review]
lgtm, assuming the testing works as expected!

**Comment by nathanleiby** [comment]
Ran `integration_test.sh` and verified no regression for Github/Gitlab, so I'll merge this and ship a release. 

I haven't tested Enterprise myself, but at that point can handoff to others for their help in testing 🙏 Thank you!

**Comment by nathanleiby** [comment]
@Line-Noise @gtorre Thanks for being able to help test!

I've shipped a release here based on this change: https://github.com/Clever/microplane/releases/tag/v0.0.28

To use Github enterprise, download this new release, then use it to run:

```
mp init --provider-url https://your-enterprise-url.com
mp clone
<etc>
```

I don't expect problems other than "it doesn't work", as there's no special logic here other than setting up the Github Enterprise client. It's using the same API calls we've tested with non-enterprise Github. Still please understand that I haven't tested this feature myself so be cautious if anything seems amiss.

Thanks again!

**Comment by gtorre** [comment]
@nathanleiby thanks! I downloaded the darwin binary and getting this error:

```
gtorre@MacBook-Pro Downloads % ./mp-0.0.28-darwin-amd64 init --provider-url https://github.example.net
2021/03/23 13:21:34 to init via code search (default), you must pass a search query. If init from a repo file, specify a repos file with -f.If init with a github repo search, include --repo-search flag.
gtorre@MacBook-Pro Downloads % ./mp-0.0.28-darwin-amd64 clone
2021/03/23 13:21:39 open /Users/gtorre/Downloads/mp/init.json: no such file or directory
```

**Comment by nathanleiby** [comment]
@gtorre Sorry for the confusion! `init` has several ways to select a list of repos. One option is to pass it a file containing the repos, with the `-f` flag.

Can you try creating a file named `repos.txt` that contains one or more projects listed in it, and pass that to init?
```
<your-org>/<your-repo1>
<your-org>/<your-repo2>
```

for example at Clever this might look like:
```
clever/microplane
clever/repo2
```

Once you've created that file, run:

`./mp-0.0.28-darwin-amd64 init --provider-url https://github.example.net -f repos.txt`

**Comment by gtorre** [comment]
@nathanleiby happy to report that it worked!

```
% ./mp-0.0.28-darwin-amd64 status
REPO		STATUS		DETAILS
halcyon		cloned
```

**Comment by nathanleiby** [comment]
@gtorre glad to hear it and thank you for testing!

**Pull request merged**
