### PR TITLE
Get DefaultBranch instead of master

### PR DESCRIPTION
**Pull request by nitrocode**
A lot of Github repos are changing their default branch from `master` to `main` or other names and so this changes the hard coded branch `master` to the `DefaultBranch` returned from the github api.

## JIRA
N/A

## Overview
- [x] Bumped up the version in VERSION file

## Rollout
N/A

### CODE REVIEW

**Comment by nitrocode** [comment]
@rgarcia friendly ping

**Comment by rgarcia** [comment]
thanks! Sorry for the delay. Was on parental leave

**Comment by nitrocode** [comment]
@rgarcia no worries. Thank you for the merge. Any chance we can do another release for `0.0.24` ? 😄

**Comment by rgarcia** [comment]
@nitrocode just released as v0.0.25

**Pull request merged**
