### PR TITLE
Create a Provider (Github/Gitlab) during init and pass it on to other steps

### PR DESCRIPTION
**Pull request by nathanleiby**
## JIRA 
n/a

## Overview

The high level goal here is to setup the provider once during
initialize. After that, all following steps will respect this
configuration.

1. created `package lib`, which now holds
  - `Provider` abstraction (for Github or Gitlab)
  - `Repo` - allows us to pass along the `Provider` configuration
2. centralized the logic to setup a Github or Gitlab client, in the
`Provider` 

This is also prep work that should help simplify adding Github Enterprise support. https://github.com/Clever/microplane/pull/44

⚠️ WARNING: This version has a breaking UX change for Gitlab users. We now pass `provider` and `provider-url` via flags instead of using env vars to determine (1) Github vs Gitlab and (2) whether or not a custom URL is set. See `README.md` regarding Gitlab. 

NOTE: There's some other cleanup here, apologies for the noise. The key commits for the provider work are:

- bc56dbb
- 72d1c01

## Testing

- [x] Test e2e for Github :octocat: 
- [x] Test e2e for Gitlab 🧪

### CODE REVIEW

**Comment by nathanleiby** [comment]
seems like CODEOWNERS auto-assignment isn't enabled

**Comment by nathanleiby** [comment]
Added an `integration_test.sh` script and caught some errors in the Gitlab (one I just introduced with this PR e56d44a, and one that existed previously e133845) with it. 🥳

**Comment by ghirsch1** [comment]
> seems like CODEOWNERS auto-assignment isn't enabled

fixed here https://github.com/Clever/microplane/commit/e6a3cda3d7f7dabe7a8326f36b3ecd807d4c5314

**Review by ghirsch1 — APPROVED** [review]
Nice refactoring, and adding the integration test looks awesome!

**Pull request merged**
