### PR TITLE
feat: Add merge-method option

### LINKED ISSUE #103: Squash instead of merge commit
Hello 👋

Thank you for this awesome project! I'd love to contribute to this project, and one thing that has bugged me a little is that I have no way to choose which kind of merge I'd like.

I would rather squash and merge than add a merge commit. I'm not sure if it's possible, but I'd love to have a go at it if that is a feature you'd like to see in Microplane!

Thanks again!

### PR DESCRIPTION
**Pull request by cobraz**
As per #103, this adds the option to set which merge method to use (e.g. squash or rebase). 

fixes #103

### CODE REVIEW

**Review by nathanleiby — CHANGES_REQUESTED** [review]
Thanks so much for the contribution! This looks great.

One small request: let's add some validation within the command to error if any invalid string value is passed (i.e. only allow "merge", "squash", and "rebase"). This way it will fail immediately at the start rather than doing a fan out and failing for all the parallelized commands.

Something like the "custom validator" logic shown here:
https://github.com/spf13/cobra/blob/master/user_guide.md#positional-and-custom-arguments

**Comment by cobraz** [comment]
Hi @nathanleiby, AFAIK, custom validation applies for the whole command (`merge` in our case), not just the flag. Trying to use something standardized, I went over to `pflag` to see what it had to offer, and find this: https://github.com/spf13/pflag/issues/236

I see four options.

1) Use/create a fork of `pflag` while spf13/pflag#236 is waiting.
2) Write custom validation for the _whole command_, like described above
3) Write something in `cmd/merge.go`
4) Let either Github or GitLab command validate it.

**Comment by nathanleiby** [comment]
@cobraz thanks for digging into this. 

Elsewhere in the repo we've followed an approach I think is (2) or (3) in your list. Here's an example of validating that the string passed to `--throttle` can be parsed as a Golang duration. Suggest that we follow the same approach here.

**Comment by nathanleiby** [comment]
@cobraz I realized I didn't link the suggested code with validation logic. I'm sorry about that! The code I meant to link is here:

https://github.com/Clever/microplane/blob/bc56dbb2d465340f766debc6781978d0e2e1098b/cmd/merge.go#L36-L47

Hope this isn't stepping on your toes too much, but I went ahead and implemented the same sort of check for `--merge-method`, so we can go ahead and merge your change. Thank you again for the the PR!

**Comment by nathanleiby** [comment]
Released here: https://github.com/Clever/microplane/releases/tag/v0.0.33

**Pull request merged**
